# ASP.NET

# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

jobs:
- job: Build
  steps:
  - task: NuGetToolInstaller@1

  - task: NuGetCommand@2
    inputs:
      restoreSolution: '$(solution)'

  - task: VSBuild@1
    inputs:
      solution: '$(solution)'
      msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'

  - task: VSTest@2
    inputs:
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'

- job: Package
  steps:
  - task: VSBuild@1
    inputs:
      solution: '**/*.sln'
      msbuildArgs: '/p:RunOctoPack=true /p:OctoPackPackageVersion=1.0.$(Build.BuildId) /p:OctoPackEnforceAddingFiles=true'

- job: Test
  steps:
  - task: VSTest@2
    inputs:
      testSelector: 'testAssemblies'
      testAssemblyVer2: |
        **\*$(buildConfiguration)\*test*.dll
        !**\obj\**
      searchFolder: '$(System.DefaultWorkingDirectory)'
      vstestLocationMethod: 'location'
      vstestLocation: '$(Agent.ToolsDirectory)/testplatform/vstest.console.exe'

- job: Deploy
  steps:
  - task: OctopusPush@6
    inputs:
      OctoConnectedServiceName: 'IbbyOpsAcct'
      Space: 'Ibby Azure DevOps'
      Replace: 'false'
